export type PatternType = 'grid' | 'circuit' | 'wave' | 'radial' | 'diagonal';
export type ToolType = 'plugin' | 'mcp' | 'skill';
export type ToolStatus = 'live' | 'dev' | 'soon';

export interface ToolEntry {
  id: string;
  name: string;
  type: ToolType;
  status: ToolStatus;
  oneliner: string;
  installCommand?: string;
  detailUrl?: string;
  accentHue: number;
  saturation: number;
  pattern: PatternType;
  gradientAngle: number;
}

export const TOOLS: ToolEntry[] = [
  {
    id: 'paid-search',
    name: 'Paid Search',
    type: 'plugin',
    status: 'live',
    oneliner: 'Google Ads management plugin for Claude Code. Write queries, analyze spend, optimize campaigns.',
    installCommand: 'claude plugin add channel47/paid-search',
    detailUrl: '/plugins/paid-search',
    accentHue: 38,
    saturation: 90,
    pattern: 'grid',
    gradientAngle: 135,
  },
  {
    id: 'meta-ads',
    name: 'Meta Ads',
    type: 'plugin',
    status: 'dev',
    oneliner: 'Facebook and Instagram ad management. Creative analysis, audience insights, budget allocation.',
    detailUrl: '/plugins/meta-ads',
    accentHue: 214,
    saturation: 80,
    pattern: 'grid',
    gradientAngle: 225,
  },
  {
    id: 'google-ads-mcp',
    name: 'Google Ads MCP',
    type: 'mcp',
    status: 'live',
    oneliner: 'Model Context Protocol server for Google Ads API. Full GAQL access from any MCP client.',
    installCommand: 'npx @anthropic-ai/google-ads-mcp',
    detailUrl: '/mcps/google-ads-mcp',
    accentHue: 142,
    saturation: 70,
    pattern: 'circuit',
    gradientAngle: 0,
  },
  {
    id: 'bing-ads-mcp',
    name: 'Bing Ads MCP',
    type: 'mcp',
    status: 'live',
    oneliner: 'Microsoft Advertising MCP server. Campaign data, keyword reports, auction insights.',
    installCommand: 'npx @channel47/bing-ads-mcp',
    detailUrl: '/mcps/bing-ads-mcp',
    accentHue: 200,
    saturation: 75,
    pattern: 'circuit',
    gradientAngle: 90,
  },
  {
    id: 'dataforseo-mcp',
    name: 'DataForSEO MCP',
    type: 'mcp',
    status: 'live',
    oneliner: 'SERP data, keyword volumes, backlinks, and competitive intelligence via MCP.',
    installCommand: 'npx @channel47/dataforseo-mcp',
    accentHue: 280,
    saturation: 65,
    pattern: 'circuit',
    gradientAngle: 180,
  },
  {
    id: 'nano-banana',
    name: 'Nano Banana',
    type: 'mcp',
    status: 'live',
    oneliner: 'Lightweight MCP server for quick API integrations. Plug in any REST endpoint.',
    installCommand: 'npx @channel47/nano-banana',
    accentHue: 55,
    saturation: 85,
    pattern: 'circuit',
    gradientAngle: 270,
  },
  {
    id: 'gaql',
    name: 'GAQL',
    type: 'skill',
    status: 'live',
    oneliner: 'Write, debug, and validate Google Ads Query Language. Schema-aware completions.',
    installCommand: 'curl -sL skills.sh/gaql | bash',
    detailUrl: '/skills/gaql',
    accentHue: 160,
    saturation: 70,
    pattern: 'wave',
    gradientAngle: 45,
  },
  {
    id: 'morning-brief',
    name: 'Morning Brief',
    type: 'skill',
    status: 'live',
    oneliner: 'Daily ad account health check. Spend pacing, anomaly detection, action items.',
    installCommand: 'curl -sL skills.sh/morning-brief | bash',
    detailUrl: '/skills/morning-brief',
    accentHue: 38,
    saturation: 90,
    pattern: 'diagonal',
    gradientAngle: 135,
  },
  {
    id: 'waste-detector',
    name: 'Waste Detector',
    type: 'skill',
    status: 'live',
    oneliner: 'Find wasted spend across campaigns. Search terms, placements, audiences leaking budget.',
    installCommand: 'curl -sL skills.sh/waste-detector | bash',
    detailUrl: '/skills/waste-detector',
    accentHue: 0,
    saturation: 75,
    pattern: 'radial',
    gradientAngle: 0,
  },
  {
    id: 'search-term-verdict',
    name: 'Search Term Verdict',
    type: 'skill',
    status: 'live',
    oneliner: 'Classify search terms as convert, consider, or kill. Bulk negative keyword management.',
    installCommand: 'curl -sL skills.sh/search-term-verdict | bash',
    detailUrl: '/skills/search-term-verdict',
    accentHue: 260,
    saturation: 70,
    pattern: 'wave',
    gradientAngle: 315,
  },
  {
    id: 'content-miner',
    name: 'Content Miner',
    type: 'skill',
    status: 'live',
    oneliner: 'Extract high-signal content from activity streams. Package for distribution.',
    installCommand: 'curl -sL skills.sh/content-miner | bash',
    accentHue: 320,
    saturation: 65,
    pattern: 'wave',
    gradientAngle: 200,
  },
  {
    id: 'prompt-optimizer',
    name: 'Prompt Optimizer',
    type: 'skill',
    status: 'live',
    oneliner: 'Transform rough prompts into structured, best-practice prompts optimized for Claude.',
    installCommand: 'curl -sL skills.sh/prompt-optimizer | bash',
    accentHue: 180,
    saturation: 60,
    pattern: 'diagonal',
    gradientAngle: 45,
  },
  {
    id: 'voice-skill-builder',
    name: 'Voice Skill Builder',
    type: 'skill',
    status: 'live',
    oneliner: 'Build a personal voice skill from writing samples. Capture tone, rhythm, vocabulary.',
    installCommand: 'curl -sL skills.sh/voice-skill-builder | bash',
    accentHue: 45,
    saturation: 80,
    pattern: 'radial',
    gradientAngle: 0,
  },
];
